/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_function_jni_JniUtils */

#ifndef _Included_com_function_jni_JniUtils
#define _Included_com_function_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_function_jni_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_function_jni_JniUtils_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_function_jni_JniUtils
 * Method:    getStringFromC2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_function_jni_JniUtils_getStringFromC2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
